# This is a basic workflow to help you get started with Actions

name: Call servicenow rest api on push or pull

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  deployment:
    runs-on: ubuntu-latest
    steps:
    - name: Deploy Stage
      uses: dkershner6/post-api-call-action@v1
      with:
        url: https://dev50344.service-now.com/api/537696/github_actions/trigger
        # JSON string of data to pass into request
        data: '{"action":" ${{ github.event.head_commit.message }} "}'
        # JSON string of headers to pass into request
        headers: '{"Content-Type": "application/json"}'
